# -*- coding: utf-8 -*-
"""Kgomotso PROJ 1 RESIDENTIAL ENERGY DEMAND FORECASTING .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Rbljepm-EoSe1AMDnitwCbugTLAMqzCm

**PROJECT 1: Predicting Residential Electricity Consumption for Infrastructure Planning at Botswana Power Corporation**

This project addresses the manual inefficiencies in estimating residential electricity demand for the Botswana Power Corporation (BPC) as urbanization expands across Gaborone. By transitioning from traditional manual estimation to a Supervised Machine Learning approach, specifically Simple Linear Regression, this study analyzes the direct relationship between a property’s physical size and its expected energy consumption. The goal is to provide a data-driven, automated system that prevents transformer overloads and optimizes resource allocation, ensuring that BPC’s infrastructure investments remain efficient, scalable, and sustainable for the national grid.

# Data Loading and Setup
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install streamlit -q

import pandas as pd

# This path points directly to your permanent Drive folder
file_path = '/content/drive/MyDrive/PROJECT 1 BPC DATA/electricity_data.csv'

# Load the dataset
df_bpc = pd.read_csv(file_path)

# Preview the data to make sure it's working
print("✅ Dataset loaded successfully from Google Drive.")
print(df_bpc.head())

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
from sklearn.linear_model import LinearRegression

# Load the data
try:
    df = pd.read_csv('electricity_data.csv')
    print("Data loaded successfully from 'electricity_data.csv'!")
except FileNotFoundError:
    print("Error: 'electricity_data.csv' not found. Please upload the file or provide the correct path.")
    print("Creating a dummy DataFrame for demonstration purposes.")
    # Create dummy data for demonstration if the file is not found
    np.random.seed(42) # for reproducibility
    square_footage = np.random.randint(450, 3000, 100)
    # Simulate a linear relationship with some noise
    monthly_kwh = 0.25 * square_footage + np.random.normal(50, 20, 100)
    monthly_kwh = np.clip(monthly_kwh, 150, 1050) # Ensure kWh stays within a reasonable range
    df = pd.DataFrame({
        'Square_Footage': square_footage,
        'Monthly_kWh': monthly_kwh
    })
    print("Dummy data created. Please replace with your actual data.")

# Set a professional style for all charts
sns.set_theme(style="whitegrid")

"""# Analysing and visualization of data.

To predicts monthly electricity usage (kWh) based on a property’s Square Footage.

#Scatter Plot

The data points form a very tight, straight diagonal blue line, indicates that as Square Footage increases, the Monthly kWh increases at a consistent and predictable rate.

In "Supervised Learning." It proves that a strong relationship exists, confirming that we can proceed with a Linear Regression model.

# Visual 1: Scatter Plot
"""

plt.figure(figsize=(8, 5))
sns.scatterplot(data=df, x='Square_Footage', y='Monthly_kWh', color='blue', s=100)
plt.title('1. Scatter Plot: Square Footage vs Monthly kWh')
plt.show()

"""# Regression Plot

The red regression line passes almost perfectly through the center of all data points. This shows that our "Line of Best Fit" has very little error.

For a utility provider, this line serves as a "Predictive Tool." It allows BPC to estimate the energy costs for a new property even if we don't have historical billing data.

# Visual 2: Regression Plot
"""

plt.figure(figsize=(8, 5))
sns.regplot(data=df, x='Square_Footage', y='Monthly_kWh', scatter_kws={'color':'blue'}, line_kws={'color':'red'})
plt.title('2. Regression Plot: Predicting Energy Consumption')
plt.show()

"""#Histogram of Square Footage

Insight: The property sizes range from 450 to 3000 sq ft, with most properties being distributed evenly. There isn't a massive cluster in just one size category.

Justification: This helps the "BI Technician" ensure the dataset is diverse. A diverse range of house sizes makes the final model more robust and applicable to both small apartments and large homes.

# Visual 3: Histogram of Square Footage
"""

plt.figure(figsize=(8, 5))
sns.histplot(df['Square_Footage'], bins=8, kde=True, color='green')
plt.title('3. Distribution of Property Sizes (Sq Ft)')
plt.show()

"""# Histogram of Monthly kWh

Similar to the size distribution, energy usage ranges from 150 to 1050 kWh. The curve shows a "Normal Distribution," which is ideal for statistical modeling.

Understanding the frequency of high-usage vs. low-usage customers helps BPC "Risk Thresholds" for utility expenses.

# Visual 4: Histogram of Monthly kWh
"""

plt.figure(figsize=(8, 5))
sns.histplot(df['Monthly_kWh'], bins=8, kde=True, color='purple')
plt.title('4. Distribution of Energy Usage (kWh)')
plt.show()

"""# Box Plot (Square Footage)

The box is centered, and there are no "dots" outside the whiskers. This means there are no extreme outliers in property size.

Outliers can "pull" the regression line in the wrong direction (skewing). This plot proves the data is clean and the house sizes are realistic.

# Visual 5: Box Plot (Square Footage)
"""

plt.figure(figsize=(8, 5))
sns.boxplot(x=df['Square_Footage'], color='cyan')
plt.title('5. Outlier Detection: Square Footage')
plt.show()

"""# Box Plot (Monthly kWh)

No extreme outliers are present in the consumption data. The median energy usage is approximately 475 kWh.

In energy prediction, an outlier might represent a faulty meter or a commercial building mixed with residential data. This visual confirms our data represents standard residential usage.

# Visual 6: Box Plot (Monthly kWh)
"""

plt.figure(figsize=(8, 5))
sns.boxplot(x=df['Monthly_kWh'], color='magenta')
plt.title('6. Outlier Detection: Monthly kWh')
plt.show()

"""# Violin Plot

Violin Plot (Monthly kWh)
The "fat" part of the violin is in the middle, showing that the most common energy consumption for these properties is between 300 and 600 kWh.

While a histogram shows counts, the violin plot shows density. It tells the business where the "majority" of the market lies, allowing for more targeted infrastructure planning.

# Visual 7: Violin Plot
"""

plt.figure(figsize=(8, 5))
sns.violinplot(y=df['Monthly_kWh'], color='yellow')
plt.title('7. Density Analysis: Monthly kWh')
plt.show()

"""# Correlation Heatmap

The correlation coefficient between Square Footage and Monthly kWh is effectively 1.00 (or very close to it).

This is the "Mathematical Proof" required by the board. A correlation of 1.00 is a perfect positive relationship, meaning size is a near-perfect predictor of energy usage in this dataset.

# Visual 8: Correlation Heatmap
"""

plt.figure(figsize=(6, 4))
sns.heatmap(df.corr(), annot=True, cmap='coolwarm', fmt=".2f")
plt.title('8. Correlation Matrix')
plt.show()

"""# Joint Plot

This combines the scatter points into "Hexagons" to show where the data is most concentrated. It confirms the density is highest in the small-to-medium property range.

By seeing both the distribution and the relationship at once, we provide a "Three - Dimensional" view of the data's reliability to the stakeholders

# Visual 9: Joint Plot
"""

# Note: JointPlot is a figure-level function and creates its own window
g = sns.jointplot(data=df, x='Square_Footage', y='Monthly_kWh', kind='hex', color='orange')
g.fig.suptitle('9. Joint Plot: Distribution & Relationship', y=1.02)
plt.show()

"""# Residual Plot

The "errors" (residuals) are scattered randomly around the horizontal zero-line. There is no clear pattern (like a U-shape) in the errors.

This is a Diagnostic Check. If the residuals had a pattern, it would mean Linear Regression is the wrong model. Because they are random, it justifies our choice of the Linear Regression algorithm.

# Visual 10: Residual Plot
"""

X = df[['Square_Footage']]
y = df['Monthly_kWh']
model = LinearRegression().fit(X, y)
y_pred = model.predict(X)
residuals = y - y_pred

plt.figure(figsize=(8, 5))
plt.scatter(y_pred, residuals, color='purple')
plt.axhline(0, color='red', linestyle='--')
plt.title('10. Residual Plot: Error Analysis')
plt.xlabel('Predicted kWh')
plt.ylabel('Residuals')
plt.show()

import joblib
# Save it directly to your permanent Drive folder
model_path = '/content/drive/MyDrive/PROJECT 1 BPC DATA/electricity_model.pkl'
joblib.dump(model, model_path)
print("Model saved permanently to Google Drive.")

from google.colab import drive
import joblib
import pandas as pd
import numpy as np

drive.mount('/content/drive')

"""#Data Cleaning

For the BPC Energy Project, Curation Pipeline was used focusing on four specific data cleaning methods. This ensures that the Linear Regression model receives "High-Integrity" data, which is essential for accurate predictions in Gaborone’s residential sector.

Here are the specific methods implemented:

1. Completeness Check (Null Handling)
Used df.isnull().sum() to scan the dataset for any missing "holes."

Why: In a small dataset of 20 houses, even one missing value can break the mathematical logic of the regression model. Confirmed the dataset was 100% complete.

2. Uniqueness Check (Duplicate Removal)
Used df.duplicated() and df.drop_duplicates() to find and remove any rows that were listed more than once.

Why: If the same 1,500 sq ft house is recorded twice, it "weights" the model too heavily toward that specific size. Removing duplicates ensures the model is "Generalized" (fair for all house sizes).

3. Consistency Check (Data Type Validation)
Used pd.to_numeric() to force the Square_Footage and Monthly_kWh columns into Float64 (numerical) format.

Why: Scikit-learn (our ML library) cannot do math on "text" or "objects." If a number was accidentally saved as text (e.g., "1200" instead of 1200), this step fixed it so the computer could process the calculation.

4. Logical Range Validation (Sanity Check)
Used df.describe() to check the Min and Max values of the data.

Why: We verified that no property had "0" or "negative" square footage. Since a house cannot have a negative size, this step ensures we aren't training the model on "impossible" data.
"""

# ==============================
# TASK 2: DATA CLEANING
# ==============================

# 1. Check the first rows
print("Preview of the dataset:")
print(df.head())

# 2. Check dataset structure
print("\nDataset Information:")
print(df.info())

# 3. Check for missing values
print("\nMissing Values:")
print(df.isnull().sum())

# 4. Remove duplicate rows
df = df.drop_duplicates()
print("\nDuplicates removed (if any).")

# 5. Confirm data types
print("\nData Types:")
print(df.dtypes)

# 6. Detect outliers using boxplot
import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(8,5))
sns.boxplot(data=df)
plt.title("Boxplot to Detect Outliers")
plt.show()

# 7. Statistical summary
print("\nStatistical Summary:")
print(df.describe())

# 8. Separate features and target variable
X = df[['Square_Footage']]   # Feature
y = df['Monthly_kWh']        # Target variable

print("\nFeatures and target variable prepared for machine learning.")

"""#Machine Learning Model
In Task 3, I implemented a Logistic Regression model to transition from value prediction to Categorical Classification. This is to assist BPC in identifying 'High-Load' households. By defining a threshold of 475 kWh, the model successfully categorizes properties based on their square footage. This is a vital business tool for BPC to target 'Energy Efficiency' campaigns toward specific residential sectors in Gaborone and it can also be useful when implimanting load management during times, where Morupule power plant's units are down and producing less energy.
"""

# ==============================
# TASK 3: LOGISTIC REGRESSION MODEL
# ==============================

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# 1. Create a classification column based on threshold
threshold = 475
df['High_Consumer'] = (df['Monthly_kWh'] > threshold).astype(int)

print("Updated dataset with classification column:")
print(df.head())

# 2. Define Features (X) and Target (y)
X = df[['Square_Footage']]
y = df['High_Consumer']

# 3. Split data into Training and Testing sets
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# 4. Create Logistic Regression Model
log_model = LogisticRegression()

# 5. Train the model
log_model.fit(X_train, y_train)

print("Logistic Regression model trained successfully!")

# 6. Make predictions
y_pred = log_model.predict(X_test)

# 7. Evaluate the model
print("\nModel Accuracy:")
print(accuracy_score(y_test, y_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

# ... (Your Linear Regression training code here) ...
# model.fit(X_train, y_train)

# SAVE THE MODEL TO DRIVE
joblib.dump(model, '/content/drive/MyDrive/PROJECT 1 BPC DATA/electricity_model.pkl')

"""#Model Performance Evaluation
The performance of the Logistic Regression model was evaluated using several classification metrics. The model’s accuracy was calculated to determine the proportion of correctly classified households. A confusion matrix was also generated to visualize the model’s performance in distinguishing between High Energy Consumers and Efficient Consumers.

Additional evaluation metrics including precision, recall, and F1-score were used to provide a more detailed understanding of the model’s performance. Precision measures the accuracy of predicted high-consumption households, while recall indicates how effectively the model identifies actual high-consumption households.

These evaluation techniques provide valuable insights into the reliability of the classification model. For Botswana Power Corporation (BPC), such insights could support targeted energy efficiency programs by accurately identifying residential areas with higher electricity demand.
"""

# ==============================
# TASK 4: MODEL EVALUATION
# ==============================

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import seaborn as sns
import matplotlib.pyplot as plt

# 1. Calculate Accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Model Accuracy:", accuracy)

# 2. Generate Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
print("\nConfusion Matrix:")
print(cm)

# 3. Visualize Confusion Matrix
plt.figure(figsize=(6,4))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=['Efficient Consumer','High Consumer'],
            yticklabels=['Efficient Consumer','High Consumer'])

plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix for Logistic Regression Model")
plt.show()

# 4. Classification Report
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

!pip install streamlit

# 1. Define the 'code' variable (This was missing!)
code = """
import streamlit as st
import pickle
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Load the model
try:
    with open('electricity_model.pkl', 'rb') as f:
        model = pickle.load(f)
except FileNotFoundError:
    st.error("Model file not found. Upload electricity_model.pkl to GitHub.")

st.title("⚡ House Electricity & Appliance Analysis")
sq_ft = st.number_input("Enter Square Footage:", min_value=100, value=1500)

if st.button("Generate Full Report"):
    prediction = model.predict(np.array([[sq_ft]]))[0]
    st.success(f"### Predicted Total: {prediction:.2f} kWh")

    # Appliance Breakdown
    st.subheader("Appliance Breakdown")
    ratios = {"HVAC": 0.45, "Water Heater": 0.18, "Laundry": 0.08, "Lights": 0.07, "Fridge": 0.05}
    data = [{"Appliance": k, "kWh": round(prediction * v, 2)} for k, v in ratios.items()]
    st.table(pd.DataFrame(data))
"""

# 2. Now write the 'code' variable to the file
with open("app.py", "w") as f:
    f.write(code.strip())

print("Success! app.py has been created in your folder.")

# CREATING A GITHUB APP FILE (BPC RESIDENTIAL ESTIMATOR)
streamlit_code = """
import streamlit as st
import joblib
import numpy as np

st.title("BPC Residential Load Estimator")
model = joblib.load('electricity_model.pkl') # GitHub version uses local path

house_size = st.slider("Select Property Size (sq ft)", 400, 5000, 1500)
if st.button("Predict"):
    prediction = model.predict(np.array([[house_size]]))
    st.success(f"Estimated Consumption: {prediction[0]:.2f} kWh")
"""

with open("app.py", "w") as f:
    f.write(streamlit_code)
print("✅ Created app.py for your GitHub repository!")

requirements = """
streamlit
pandas
numpy
scikit-learn
matplotlib
joblib
"""

with open("requirements.txt", "w") as f:
    f.write(requirements.strip())

print("requirements.txt has been created with joblib included!")

# FINAL SECTION: PREDICTION ---

import joblib
import numpy as np

# 1. The "Brain" you saved earlier
# This ensures that restart Colab, to still make predictions
model = joblib.load('/content/drive/MyDrive/PROJECT 1 BPC DATA/electricity_model.pkl')
print("✅ Model loaded successfully from Drive.")

# 2. Testing the model with a new value
# Let's say a BPC customer has a 1500 sq ft house
house_size = 1500
sample_house = np.array([[house_size]])

# 3. Get the prediction
prediction = model.predict(sample_house)

print(f"--- BPC Load Estimation ---")
print(f"Property Size: {house_size} sq ft")
print(f"Estimated Consumption: {prediction[0]:.2f} kWh")

#@title BPC Residential Estimator
house_size = 1500 #@param {type:"slider", min:400, max:5000, step:50}